#version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: oraculista
      POSTGRES_USER: oraculista
      POSTGRES_PASSWORD: oraculista
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5442:5432"

  cms:
    image: node:20-alpine
    user: "0:0"
    working_dir: /srv/app
    command: sh -c "npm install && npm run develop"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: oraculista
      DATABASE_USERNAME: oraculista
      DATABASE_PASSWORD: oraculista
      DATABASE_SSL: "false"
      ADMIN_JWT_SECRET: "0ph7Tu1axZco3jm82nszrCEWevSLJ5RYMAq4tVDyIgNfFbPdk6iOKHlUXQw9BG"
      API_TOKEN_SALT: "TYnqNGKgMr21ZHWXV53bRLEOmSwaz9vUsIfydi0DQoltpej8FBcukxhC4JAP67"
      TRANSFER_TOKEN_SALT: "78Mmv2Vb5jdoIiYfFUcKJqlBQLwPxpS6ZrDGWHRn9EXyhO1g0Aats3CT4eNuzk"
      ENCRYPTION_KEY: "QbUToRrf95K6Yj8wW1Zq4msNB0lecC3tiJyMApDvFkIXgdPznGuxahES2HOL7V"
      APP_KEYS: "0ph7Tu1axZco3jm82nszrCEWevSLJ5RYMAq4tVDyIgNfFbPdk6iOKHlUXQw9BG,TYnqNGKgMr21ZHWXV53bRLEOmSwaz9vUsIfydi0DQoltpej8FBcukxhC4JAP67,78Mmv2Vb5jdoIiYfFUcKJqlBQLwPxpS6ZrDGWHRn9EXyhO1g0Aats3CT4eNuzk,QbUToRrf95K6Yj8wW1Zq4msNB0lecC3tiJyMApDvFkIXgdPznGuxahES2HOL7V"
      NODE_ENV: development
    volumes:
      - ./cms:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - db

  web:
    image: node:20-alpine
    user: "0:0"
    working_dir: /srv/app
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
      STRAPI_URL: http://cms:1337
    volumes:
      - ./web:/srv/app
    ports:
      - "3101:3000"

volumes:
  postgres_data:
